### ISSUE TITLE
Open-source license?

### ISSUE THREAD

**Issue by epeli** [flysight/flysight#60]
Hi!

In your README you state that this project is an open-source but I cannot find a LICENSE file. What's the license?

**Comment by mlambie** [comment]
Is there any update on this at all?

**Comment by crwper** [comment]
Ah, this one slipped completely off the radar. It's taken me a long time to look at specific licenses, but I'm considering GPLv3 for source code. Any comments?

**Comment by willglynn** [comment]
@crwper Three thoughts:

1. The firmware statically links LUFA ([~MIT license](https://github.com/abcminiuser/lufa/blob/b6c18b2a7c544653efbe12a1d4e8ba65e7d83c35/LUFA/License.txt)), so `flysight/flysight`'s license needs to be compatible with the reality that it integrates with that project.
2. [`flysight/flysight` contributors](https://github.com/flysight/flysight/graphs/contributors) might have opinions to consider. (This is a gray area.) That's almost entirely you, a little bit me, a little bit @tvandijck, and possibly soon @richo.
3. The license goals are unclear to me and are probably worth spelling out. For example: are you worried about someone forking the project, adding features, and charging for their derived firmware? Are you worried about someone taking the project, building their own similar hardware, and selling a competing device? Are you worried about software patents, especially as they relate to integrating contributions?

Speaking for myself, I am generally not worried about any of these things. ¯\\\_(ツ)\_/¯ Any hypothetical future changes that I don't like wouldn't affect the FlySight in my gear bag unless I went out of my way to flash it, and the hardware limits the scope of potential improvements. In this context, I'd be happy with any OSI-approved license.

**Comment by crwper** [comment]
@willglynn Great comments as always. In the firmware I believe use the following libraries:

- FatFS (statically linked): Free software with no restrictions on use. I don't think it's a "canned" license.
- LUFA (statically linked): MIT

For  FlySight Viewer we have:

- GeographicLib (statically linked): MIT
- VLC (dynamically linked): GPLv2
- wwWidgets (dynamically linked): GPLv2
- Qt (dynamically linked): LGPL v3
- VLCQt (dynamically linked): LGPL v3

As I understand it, by dynamically linking a library, we are firmly in the camp of "products that use the library", as opposed to "derivative works". Even for GPL, it seems to me that this places very few limits on our own licensing.

I'm a bit confused by the licensing for Qt, since they make a pretty big deal of the distinction between their commercial and open source licenses, but then they seem to be licensing using LGPL, which I believe does not force the linking application to share source code. Am I missing a detail here?

If I've understood all of this correctly, we could use either MIT or GPL/LGPL for both the firmware and FlySight Viewer. Does that sound right?

I think the main choice here is between a less restrictive licensing scheme (MIT/LGPL) and a more restrictive one (GPL). I've generally thought of both the firmware and FlySight Viewer as an end product, and unlikely to inspire derivative works. However, I suppose it's more likely that someone would use one or two source files in their own application--e.g., something like the genetic optimization. The main question, I think, is whether I think it's necessary to strong-arm someone into releasing their own source code as well. Any subtleties you think I should be considering?

**Comment by crwper** [comment]
If I tag other GitHub users in this discussion, will they be notified? @Luke900 has created one of the most widely-used branches of the FlySight firmware, FlyBlind, so I'd like to get his thoughts as well.

**Comment by willglynn** [comment]
@crwper The GPL doesn't distinguish static versus dynamic linking, per [the FAQ](https://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic):

> **Does the GPL have different requirements for statically vs dynamically linked modules with a covered work?** (#GPLStaticVsDynamic)
>
> No. Linking a GPL covered work statically or dynamically with other modules is making a combined work based on the GPL covered work. Thus, the terms and conditions of the GNU General Public License cover the whole combination. See also [What legal issues come up if I use GPL-incompatible libraries with GPL software?](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs)

Linkage [matters for the LGPL](https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic) and in some other situations:

> **Does the LGPL have different requirements for statically vs dynamically linked modules with a covered work?** (#LGPLStaticVsDynamic)
>
> For the purpose of complying with the LGPL (any extant version: v2, v2.1 or v3):
> 
> (1) If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.
> 
> (2) If you dynamically link against an LGPL'd library already present on the user's computer, you need not convey the library's source. On the other hand, if you yourself convey the executable LGPL'd library along with your application, whether linked with statically or dynamically, you must also convey the library's sources, in one of the ways for which the LGPL provides.

---

There is a sort of violence to the GPL – the strong-arming you mention – but I've come to understand it a few different ways over the years. Nowadays I see parallels with why tolerant societies must be intolerant of intolerance, or why civil liberties organizations must intercede on behalf of distasteful clients. The GPL takes a principled stand in favor of the user's freedom to tinker with their software. In order to do so, it must take away your options – specifically, you are not permitted to take away the user's freedoms.

The necessity of this boils down to your personal opinion. For me, I generally do not write software to take a principled stand in favor of freedoms; I generally write software because doing so will solve a problem that I have. Open source software certainly seems more pragmatic than free software: OSS has fewer restrictions, which often translates to more use cases, more collaborators, and more end users. At the same time, open source software is free to become less free, just like a society that tolerates intolerance becomes less tolerant, or how a civil liberties organization that's choosy about their clients ends up eroding the liberties they seek to protect. Free software is free software _because of_ the things you can't do.

Is this a concern you have for FlySight? ¯\\\_(ツ)\_/¯ I'll respect whatever position you take. I would have done the same things with `flysight/flysight` whether or not it's free-as-in-freedom software, which is why I didn't force the question before opening pull requests :-)

**Comment by richo** [comment]
FWIW as a future-maybe-contributor I'm fine with any of the licenses you're talking about. I have a weak preference for MIT, but don't really have a horse in this race. I'm also happy to delegate copyright/attest to relicensing anything that lands before a license shows up.

**Comment by crwper** [comment]
Just came across another dependency in the FlySight Viewer source code:

- QCustomPlot (statically linked): GPLv3

I've always had a soft spot in my heart for the MIT license, for reasons similar to those mentioned by @willglynn. When I strip everything else away, the reason I write an application like FlySight Viewer is to help the community around me. That purpose is served, I think, whether or not a third party decides to use the source code in a closed application.

However, there is also a part of me that wants to change the world a little bit. I've benefited greatly from the availability of software like Inkscape and GIMP, which are licensed under GPL. I've been inspired by companies like Lulzbot, who have released their hardware and software under GPL and CC BY-SA. Part of the reason I've kept FlySight Viewer open source is to give back to that community. I think if a third party wanted to use FlySight Viewer's code in their own application, a more restrictive license might encourage them to open up their application as well. Despite the "violence" inherent in this kind of coercion, I think we would all be better off for it.

For these reasons, I think I will go with GPLv3 for both FlySight Viewer and the FlySight firmware. I am currently working on some changes in FlySight Viewer, but as soon as that's done I will update the licenses for both.

**Comment by crwper** [comment]
I also wanted to say thanks for your contributions, both in this discussion and in the repositories. I hope that this choice of license will serve you guys as well as it does me.

**Comment by tvandijck** [comment]
Just to make a formal statement for the records.... I have no objections to re-licensing under GPLv3.

That said, going to a more restrictive license is hard. Existing forks can either decide to remain under the old license, and hence can still remain as a 'source' for companies out there to replicate your results without being restricted by the GPLv3. In other word, the license you choose today, only applies from today forwards.

**Comment by willglynn** [comment]
@tvandijck In this case, the old source has [no license](https://choosealicense.com/no-permission/). @crwper could argue that no one has any rights to the code except under the new license, and that position has merit.

The [GitHub ToS](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users) confers limited rights to see and fork the repo, so existing forks have the right to exist. However, there's nothing granting the right to edit it, build it, or use the resulting binaries. Without an additional license, existing forks remain subject to @crwper's copyright prerogatives.

People have [complained for years](https://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html) that GitHub makes public-but-unlicensed code into a common problem. Hashing it out would make some interesting case law. 🍿

**Comment by crwper** [comment]
I've added a GPLv3 license to both the firmware and FlySight Viewer. Other repositories (e.g., FlySight Configurator) will follow shortly. I believe I've correctly added attribution for all the files you guys worked on, but if I missed something then please let me know.
