### ISSUE TITLE
Publishing keys present in repository

### ISSUE THREAD

**Issue by lacasseio** [flysight/flysight#91]
I fear all the information for pushing random binaries to the publishing portal are available in the clear inside the [Travis configuration file](https://github.com/flysight/flysight/blob/master/.travis.yml#L13-L19). I haven't tried it as, if successful, could allow publishing random binaries. If this isn't intended, the key should be changed and moved to the private Travis configuration.

**Comment by willglynn** [comment]
Anyone can put in a PR and look at the build report or artifacts, e.g. #85 => [Travis build](https://travis-ci.org/flysight/flysight/builds/348533485#L616) => https://flysight-ci.herokuapp.com/builds/144. The ability to point to compiled code in a PR context is the main reason for that app; it can provide access to compiled binaries, but they're not all from `master`. I don't see that encrypting the key changes anything, since anyone can still open a PR containing arbitrary code and push it to the same place.
